import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import GradualBlur from "./components/GradualBlur/GradualBlur";
import Silk from "./components/Silk/Silk";
import SplashScreen from "./components/SplashScreen/SplashScreen";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "DwiponcoSuripto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SplashScreen />

        <div className="fixed inset-0 -z-10 pointer-events-none">
          <Silk
            speed={5}
            scale={1}
            color="#3FA9C9"
            noiseIntensity={10}
            rotation={0}
          />
        </div>

        <div className="relative z-10">{children}</div>

        <GradualBlur
          target="page"
          position="bottom"
          height="7rem"
          strength={2}
          divCount={5}
          curve="bezier"
          exponential
          opacity={1}
        />
      </body>
    </html>
  );
}
